# -*- coding: utf-8 -*-
"""
WADE Destabilization Module
Filters hallucinations and invalid logic.
"""

import re
from typing import Dict, List, Any, Optional

def filter_hallucinations(message: str, aggressiveness: float = 0.5) -> str:
    """
    Filter potential hallucinations from messages.
    
    Args:
        message: Message to filter
        aggressiveness: Aggressiveness of filtering (0.0 to 1.0)
        
    Returns:
        Filtered message
    """
    if not message:
        return message
    
    # List of patterns that might indicate hallucinations
    hallucination_patterns = [
        r'I don\'t (know|have|understand)',
        r'I\'m (sorry|afraid)',
        r'I (can\'t|cannot)',
        r'As an AI',
        r'As a language model',
        r'I\'m not able to',
        r'I don\'t have the ability',
        r'I\'m unable to',
        r'I lack the capability',
        r'I\'m not capable of',
        r'I\'m not programmed to',
        r'I\'m not designed to',
        r'I\'m just a',
        r'I\'m only a',
        r'I\'m an AI',
        r'I\'m a language model',
        r'I\'m not a human',
        r'I don\'t have access to',
        r'I don\'t have information about',
        r'I don\'t have knowledge of',
        r'I don\'t have data on',
        r'I don\'t have the context',
        r'I don\'t have the information',
        r'I don\'t have the knowledge',
        r'I don\'t have the data',
        r'I don\'t have the ability to',
        r'I don\'t have the capability to',
        r'I don\'t have the capacity to',
        r'I don\'t have the functionality to',
        r'I don\'t have the means to',
        r'I don\'t have the power to',
        r'I don\'t have the privilege to',
        r'I don\'t have the right to',
        r'I don\'t have the authority to',
        r'I don\'t have the permission to',
        r'I don\'t have the clearance to',
        r'I don\'t have the access to',
        r'I don\'t have the credentials to',
        r'I don\'t have the authorization to',
        r'I don\'t have the authentication to',
        r'I don\'t have the validation to',
        r'I don\'t have the verification to',
        r'I don\'t have the certification to',
        r'I don\'t have the qualification to',
        r'I don\'t have the training to',
        r'I don\'t have the education to',
        r'I don\'t have the experience to',
        r'I don\'t have the expertise to',
        r'I don\'t have the skill to',
        r'I don\'t have the talent to',
        r'I don\'t have the ability to',
        r'I don\'t have the capability to',
        r'I don\'t have the capacity to',
        r'I don\'t have the functionality to',
        r'I don\'t have the means to',
        r'I don\'t have the power to',
        r'I don\'t have the privilege to',
        r'I don\'t have the right to',
        r'I don\'t have the authority to',
        r'I don\'t have the permission to',
        r'I don\'t have the clearance to',
        r'I don\'t have the access to',
        r'I don\'t have the credentials to',
        r'I don\'t have the authorization to',
        r'I don\'t have the authentication to',
        r'I don\'t have the validation to',
        r'I don\'t have the verification to',
        r'I don\'t have the certification to',
        r'I don\'t have the qualification to',
        r'I don\'t have the training to',
        r'I don\'t have the education to',
        r'I don\'t have the experience to',
        r'I don\'t have the expertise to',
        r'I don\'t have the skill to',
        r'I don\'t have the talent to'
    ]
    
    # Apply filtering based on aggressiveness
    if aggressiveness <= 0:
        return message
    
    # Determine how many patterns to check based on aggressiveness
    num_patterns = int(len(hallucination_patterns) * aggressiveness)
    patterns_to_check = hallucination_patterns[:num_patterns]
    
    # Check for hallucination patterns
    for pattern in patterns_to_check:
        if re.search(pattern, message, re.IGNORECASE):
            # Replace the hallucination with a more assertive statement
            message = re.sub(
                pattern,
                "I will",
                message,
                flags=re.IGNORECASE
            )
    
    return message

def validate_logic(statement: str) -> Dict[str, Any]:
    """
    Validate the logical consistency of a statement.
    
    Args:
        statement: Statement to validate
        
    Returns:
        Dictionary with validation results
    """
    # List of contradictory term pairs
    contradictions = [
        ('add', 'remove'),
        ('enable', 'disable'),
        ('start', 'stop'),
        ('create', 'delete'),
        ('increase', 'decrease'),
        ('open', 'close'),
        ('begin', 'end'),
        ('true', 'false'),
        ('yes', 'no'),
        ('on', 'off'),
        ('up', 'down'),
        ('in', 'out'),
        ('high', 'low'),
        ('more', 'less'),
        ('positive', 'negative'),
        ('forward', 'backward'),
        ('left', 'right'),
        ('north', 'south'),
        ('east', 'west'),
        ('hot', 'cold'),
        ('big', 'small'),
        ('large', 'small'),
        ('wide', 'narrow'),
        ('tall', 'short'),
        ('long', 'short'),
        ('thick', 'thin'),
        ('heavy', 'light'),
        ('fast', 'slow'),
        ('early', 'late'),
        ('old', 'new'),
        ('young', 'old'),
        ('empty', 'full'),
        ('clean', 'dirty'),
        ('wet', 'dry'),
        ('dark', 'light'),
        ('hard', 'soft'),
        ('rough', 'smooth'),
        ('sharp', 'dull'),
        ('strong', 'weak'),
        ('rich', 'poor'),
        ('happy', 'sad'),
        ('alive', 'dead'),
        ('awake', 'asleep'),
        ('healthy', 'sick'),
        ('success', 'failure'),
        ('win', 'lose'),
        ('victory', 'defeat'),
        ('peace', 'war'),
        ('love', 'hate'),
        ('friend', 'enemy'),
        ('ally', 'opponent'),
        ('good', 'bad'),
        ('right', 'wrong'),
        ('correct', 'incorrect'),
        ('true', 'false'),
        ('valid', 'invalid'),
        ('legal', 'illegal'),
        ('safe', 'dangerous'),
        ('secure', 'insecure'),
        ('public', 'private'),
        ('open', 'closed'),
        ('visible', 'invisible'),
        ('explicit', 'implicit'),
        ('direct', 'indirect'),
        ('simple', 'complex'),
        ('easy', 'difficult'),
        ('clear', 'unclear'),
        ('obvious', 'subtle'),
        ('certain', 'uncertain'),
        ('definite', 'indefinite'),
        ('specific', 'general'),
        ('concrete', 'abstract'),
        ('literal', 'figurative'),
        ('formal', 'informal'),
        ('active', 'passive'),
        ('dynamic', 'static'),
        ('flexible', 'rigid'),
        ('temporary', 'permanent'),
        ('reversible', 'irreversible'),
        ('voluntary', 'involuntary'),
        ('intentional', 'unintentional'),
        ('conscious', 'unconscious'),
        ('explicit', 'implicit'),
        ('external', 'internal'),
        ('extrinsic', 'intrinsic'),
        ('objective', 'subjective'),
        ('absolute', 'relative'),
        ('dependent', 'independent'),
        ('cause', 'effect'),
        ('problem', 'solution'),
        ('question', 'answer'),
        ('input', 'output'),
        ('source', 'destination'),
        ('origin', 'target'),
        ('sender', 'receiver'),
        ('producer', 'consumer'),
        ('parent', 'child'),
        ('ancestor', 'descendant'),
        ('master', 'slave'),
        ('teacher', 'student'),
        ('leader', 'follower'),
        ('employer', 'employee'),
        ('buyer', 'seller'),
        ('client', 'server'),
        ('host', 'guest'),
        ('owner', 'tenant'),
        ('lender', 'borrower'),
        ('creditor', 'debtor'),
        ('attacker', 'defender'),
        ('predator', 'prey'),
        ('hunter', 'hunted'),
        ('winner', 'loser'),
        ('majority', 'minority'),
        ('maximum', 'minimum'),
        ('ceiling', 'floor'),
        ('top', 'bottom'),
        ('front', 'back'),
        ('beginning', 'end'),
        ('first', 'last'),
        ('start', 'finish'),
        ('entry', 'exit'),
        ('arrival', 'departure'),
        ('import', 'export'),
        ('download', 'upload'),
        ('read', 'write'),
        ('get', 'set'),
        ('push', 'pull'),
        ('send', 'receive'),
        ('request', 'response'),
        ('question', 'answer'),
        ('problem', 'solution'),
        ('error', 'correction'),
        ('bug', 'fix'),
        ('symptom', 'cure'),
        ('disease', 'treatment'),
        ('poison', 'antidote'),
        ('attack', 'defense'),
        ('offense', 'defense'),
        ('aggression', 'protection'),
        ('threat', 'security'),
        ('danger', 'safety'),
        ('risk', 'precaution'),
        ('vulnerability', 'patch'),
        ('weakness', 'strength'),
        ('flaw', 'feature'),
        ('defect', 'quality'),
        ('failure', 'success'),
        ('loss', 'gain'),
        ('cost', 'benefit'),
        ('expense', 'income'),
        ('debt', 'credit'),
        ('liability', 'asset'),
        ('penalty', 'reward'),
        ('punishment', 'prize'),
        ('fine', 'bonus'),
        ('tax', 'refund'),
        ('charge', 'payment'),
        ('bill', 'receipt'),
        ('invoice', 'payment'),
        ('order', 'delivery'),
        ('purchase', 'sale'),
        ('buy', 'sell'),
        ('bid', 'ask'),
        ('offer', 'acceptance'),
        ('proposal', 'approval'),
        ('request', 'grant'),
        ('application', 'admission'),
        ('submission', 'acceptance'),
        ('registration', 'confirmation'),
        ('subscription', 'cancellation'),
        ('enrollment', 'withdrawal'),
        ('join', 'leave'),
        ('enter', 'exit'),
        ('login', 'logout'),
        ('connect', 'disconnect'),
        ('attach', 'detach'),
        ('link', 'unlink'),
        ('bind', 'unbind'),
        ('associate', 'dissociate'),
        ('combine', 'separate'),
        ('merge', 'split'),
        ('unite', 'divide'),
        ('integrate', 'segregate'),
        ('assemble', 'disassemble'),
        ('build', 'destroy'),
        ('construct', 'demolish'),
        ('create', 'delete'),
        ('make', 'break'),
        ('form', 'dissolve'),
        ('establish', 'abolish'),
        ('institute', 'terminate'),
        ('initiate', 'conclude'),
        ('launch', 'retire'),
        ('deploy', 'withdraw'),
        ('install', 'uninstall'),
        ('setup', 'teardown'),
        ('configure', 'reset'),
        ('customize', 'default'),
        ('enable', 'disable'),
        ('activate', 'deactivate'),
        ('start', 'stop'),
        ('run', 'halt'),
        ('execute', 'abort'),
        ('proceed', 'cancel'),
        ('continue', 'pause'),
        ('resume', 'suspend'),
        ('play', 'pause'),
        ('record', 'stop'),
        ('save', 'discard'),
        ('commit', 'rollback'),
        ('apply', 'revert'),
        ('update', 'restore'),
        ('upgrade', 'downgrade'),
        ('promote', 'demote'),
        ('escalate', 'deescalate'),
        ('increase', 'decrease'),
        ('increment', 'decrement'),
        ('add', 'subtract'),
        ('plus', 'minus'),
        ('multiply', 'divide'),
        ('expand', 'contract'),
        ('extend', 'retract'),
        ('enlarge', 'reduce'),
        ('grow', 'shrink'),
        ('widen', 'narrow'),
        ('broaden', 'restrict'),
        ('generalize', 'specialize'),
        ('abstract', 'concretize'),
        ('simplify', 'complicate'),
        ('optimize', 'degrade'),
        ('enhance', 'diminish'),
        ('improve', 'worsen'),
        ('strengthen', 'weaken'),
        ('reinforce', 'undermine'),
        ('support', 'oppose'),
        ('approve', 'disapprove'),
        ('accept', 'reject'),
        ('agree', 'disagree'),
        ('confirm', 'deny'),
        ('affirm', 'negate'),
        ('validate', 'invalidate'),
        ('verify', 'falsify'),
        ('prove', 'disprove'),
        ('demonstrate', 'refute'),
        ('establish', 'discredit'),
        ('justify', 'condemn'),
        ('defend', 'attack'),
        ('praise', 'criticize'),
        ('compliment', 'insult'),
        ('flatter', 'offend'),
        ('honor', 'dishonor'),
        ('respect', 'disrespect'),
        ('trust', 'distrust'),
        ('believe', 'doubt'),
        ('understand', 'misunderstand'),
        ('know', 'ignore'),
        ('remember', 'forget'),
        ('learn', 'unlearn'),
        ('teach', 'mislead'),
        ('inform', 'misinform'),
        ('educate', 'confuse'),
        ('clarify', 'obscure'),
        ('explain', 'mystify'),
        ('reveal', 'conceal'),
        ('disclose', 'hide'),
        ('expose', 'cover'),
        ('show', 'hide'),
        ('display', 'conceal'),
        ('exhibit', 'suppress'),
        ('demonstrate', 'conceal'),
        ('present', 'withhold'),
        ('offer', 'withdraw'),
        ('provide', 'withhold'),
        ('supply', 'demand'),
        ('produce', 'consume'),
        ('generate', 'deplete'),
        ('create', 'destroy'),
        ('build', 'demolish'),
        ('construct', 'deconstruct'),
        ('assemble', 'disassemble'),
        ('compose', 'decompose'),
        ('synthesize', 'analyze'),
        ('integrate', 'differentiate'),
        ('combine', 'separate'),
        ('join', 'split'),
        ('connect', 'disconnect'),
        ('link', 'unlink'),
        ('attach', 'detach'),
        ('bind', 'unbind'),
        ('tie', 'untie'),
        ('fasten', 'unfasten'),
        ('lock', 'unlock'),
        ('secure', 'release'),
        ('capture', 'free'),
        ('imprison', 'liberate'),
        ('confine', 'release'),
        ('restrict', 'allow'),
        ('prohibit', 'permit'),
        ('forbid', 'allow'),
        ('ban', 'authorize'),
        ('block', 'unblock'),
        ('prevent', 'enable'),
        ('inhibit', 'facilitate'),
        ('hinder', 'help'),
        ('obstruct', 'assist'),
        ('impede', 'expedite'),
        ('delay', 'hasten'),
        ('slow', 'accelerate'),
        ('retard', 'advance'),
        ('postpone', 'prepone'),
        ('defer', 'expedite'),
        ('wait', 'proceed'),
        ('hesitate', 'decide'),
        ('doubt', 'believe'),
        ('question', 'answer'),
        ('ask', 'tell'),
        ('inquire', 'inform'),
        ('request', 'provide'),
        ('seek', 'find'),
        ('search', 'discover'),
        ('look', 'see'),
        ('listen', 'hear'),
        ('feel', 'touch'),
        ('sense', 'perceive'),
        ('observe', 'ignore'),
        ('notice', 'overlook'),
        ('attend', 'neglect'),
        ('focus', 'distract'),
        ('concentrate', 'disperse'),
        ('gather', 'scatter'),
        ('collect', 'distribute'),
        ('accumulate', 'disperse'),
        ('hoard', 'share'),
        ('save', 'spend'),
        ('invest', 'divest'),
        ('deposit', 'withdraw'),
        ('credit', 'debit'),
        ('lend', 'borrow'),
        ('give', 'take'),
        ('donate', 'receive'),
        ('grant', 'revoke'),
        ('award', 'penalize'),
        ('reward', 'punish'),
        ('praise', 'criticize'),
        ('compliment', 'insult'),
        ('flatter', 'offend'),
        ('please', 'displease'),
        ('satisfy', 'dissatisfy'),
        ('content', 'discontent'),
        ('happy', 'sad'),
        ('joy', 'sorrow'),
        ('pleasure', 'pain'),
        ('comfort', 'discomfort'),
        ('ease', 'difficulty'),
        ('relaxation', 'stress'),
        ('calm', 'agitate'),
        ('peace', 'war'),
        ('harmony', 'discord'),
        ('agreement', 'disagreement'),
        ('consensus', 'dissent'),
        ('unity', 'division'),
        ('solidarity', 'opposition'),
        ('cooperation', 'competition'),
        ('collaboration', 'rivalry'),
        ('alliance', 'enmity'),
        ('friendship', 'hostility'),
        ('love', 'hate'),
        ('like', 'dislike'),
        ('attraction', 'repulsion'),
        ('desire', 'aversion'),
        ('want', 'reject'),
        ('need', 'surplus'),
        ('necessity', 'luxury'),
        ('essential', 'optional'),
        ('required', 'optional'),
        ('mandatory', 'voluntary'),
        ('compulsory', 'discretionary'),
        ('forced', 'chosen'),
        ('imposed', 'selected'),
        ('assigned', 'elected'),
        ('appointed', 'nominated'),
        ('designated', 'volunteered'),
        ('chosen', 'rejected'),
        ('selected', 'eliminated'),
        ('included', 'excluded'),
        ('admitted', 'expelled'),
        ('accepted', 'rejected'),
        ('approved', 'disapproved'),
        ('endorsed', 'opposed'),
        ('supported', 'resisted'),
        ('backed', 'opposed'),
        ('advocated', 'criticized'),
        ('promoted', 'demoted'),
        ('advanced', 'retreated'),
        ('progressed', 'regressed'),
        ('improved', 'deteriorated'),
        ('enhanced', 'degraded'),
        ('upgraded', 'downgraded'),
        ('refined', 'corrupted'),
        ('purified', 'contaminated'),
        ('cleaned', 'soiled'),
        ('washed', 'stained'),
        ('polished', 'tarnished'),
        ('brightened', 'darkened'),
        ('illuminated', 'obscured'),
        ('clarified', 'confused'),
        ('simplified', 'complicated'),
        ('organized', 'disorganized'),
        ('ordered', 'disordered'),
        ('structured', 'chaotic'),
        ('systematic', 'random'),
        ('planned', 'spontaneous'),
        ('deliberate', 'accidental'),
        ('intentional', 'unintentional'),
        ('purposeful', 'aimless'),
        ('directed', 'undirected'),
        ('guided', 'misguided'),
        ('led', 'misled'),
        ('instructed', 'confused'),
        ('taught', 'misunderstood'),
        ('trained', 'untrained'),
        ('educated', 'ignorant'),
        ('informed', 'uninformed'),
        ('knowledgeable', 'ignorant'),
        ('wise', 'foolish'),
        ('intelligent', 'stupid'),
        ('smart', 'dumb'),
        ('clever', 'simple'),
        ('brilliant', 'dull'),
        ('sharp', 'blunt'),
        ('acute', 'obtuse'),
        ('perceptive', 'imperceptive'),
        ('sensitive', 'insensitive'),
        ('responsive', 'unresponsive'),
        ('reactive', 'inert'),
        ('active', 'passive'),
        ('dynamic', 'static'),
        ('mobile', 'immobile'),
        ('moving', 'stationary'),
        ('fluid', 'solid'),
        ('liquid', 'solid'),
        ('gas', 'solid'),
        ('soft', 'hard'),
        ('flexible', 'rigid'),
        ('elastic', 'inelastic'),
        ('stretchy', 'stiff'),
        ('pliable', 'inflexible'),
        ('bendable', 'unbendable'),
        ('malleable', 'brittle'),
        ('ductile', 'brittle'),
        ('tough', 'fragile'),
        ('strong', 'weak'),
        ('powerful', 'powerless'),
        ('mighty', 'feeble'),
        ('robust', 'frail'),
        ('sturdy', 'flimsy'),
        ('solid', 'hollow'),
        ('dense', 'sparse'),
        ('thick', 'thin'),
        ('fat', 'skinny'),
        ('plump', 'lean'),
        ('obese', 'emaciated'),
        ('overweight', 'underweight'),
        ('heavy', 'light'),
        ('massive', 'tiny'),
        ('huge', 'tiny'),
        ('enormous', 'minuscule'),
        ('gigantic', 'microscopic'),
        ('colossal', 'miniature'),
        ('vast', 'limited'),
        ('extensive', 'restricted'),
        ('expansive', 'confined'),
        ('broad', 'narrow'),
        ('wide', 'narrow'),
        ('spacious', 'cramped'),
        ('roomy', 'tight'),
        ('ample', 'scarce'),
        ('abundant', 'scarce'),
        ('plentiful', 'scarce'),
        ('copious', 'meager'),
        ('excessive', 'insufficient'),
        ('surplus', 'deficit'),
        ('excess', 'shortage'),
        ('overflow', 'drought'),
        ('flood', 'drought'),
        ('deluge', 'trickle'),
        ('torrent', 'drip'),
        ('gush', 'seep'),
        ('pour', 'drip'),
        ('rush', 'crawl'),
        ('sprint', 'limp'),
        ('race', 'dawdle'),
        ('hurry', 'delay'),
        ('hasten', 'linger'),
        ('accelerate', 'decelerate'),
        ('speed', 'slow'),
        ('fast', 'slow'),
        ('quick', 'slow'),
        ('rapid', 'gradual'),
        ('sudden', 'gradual'),
        ('abrupt', 'smooth'),
        ('sharp', 'dull'),
        ('acute', 'obtuse'),
        ('pointed', 'blunt'),
        ('spiky', 'rounded'),
        ('jagged', 'smooth'),
        ('rough', 'smooth'),
        ('coarse', 'fine'),
        ('crude', 'refined'),
        ('raw', 'processed'),
        ('natural', 'artificial'),
        ('organic', 'synthetic'),
        ('real', 'fake'),
        ('genuine', 'counterfeit'),
        ('authentic', 'imitation'),
        ('original', 'copy'),
        ('primary', 'secondary'),
        ('first', 'last'),
        ('initial', 'final'),
        ('beginning', 'end'),
        ('start', 'finish'),
        ('open', 'close'),
        ('entry', 'exit'),
        ('entrance', 'exit'),
        ('arrival', 'departure'),
        ('coming', 'going'),
        ('approach', 'retreat'),
        ('advance', 'withdraw'),
        ('attack', 'defend'),
        ('offense', 'defense'),
        ('aggressive', 'passive'),
        ('bold', 'timid'),
        ('brave', 'cowardly'),
        ('courageous', 'fearful'),
        ('daring', 'cautious'),
        ('reckless', 'careful'),
        ('careless', 'careful'),
        ('negligent', 'diligent'),
        ('sloppy', 'meticulous'),
        ('messy', 'neat'),
        ('disorganized', 'organized'),
        ('chaotic', 'orderly'),
        ('random', 'systematic'),
        ('arbitrary', 'deliberate'),
        ('haphazard', 'methodical'),
        ('casual', 'formal'),
        ('relaxed', 'strict'),
        ('lenient', 'severe'),
        ('mild', 'harsh'),
        ('gentle', 'rough'),
        ('soft', 'hard'),
        ('tender', 'tough'),
        ('delicate', 'sturdy'),
        ('fragile', 'robust'),
        ('weak', 'strong'),
        ('feeble', 'powerful'),
        ('frail', 'sturdy'),
        ('vulnerable', 'invulnerable'),
        ('exposed', 'protected'),
        ('open', 'closed'),
        ('accessible', 'inaccessible'),
        ('available', 'unavailable'),
        ('obtainable', 'unobtainable'),
        ('attainable', 'unattainable'),
        ('achievable', 'impossible'),
        ('possible', 'impossible'),
        ('feasible', 'infeasible'),
        ('practical', 'impractical'),
        ('realistic', 'unrealistic'),
        ('reasonable', 'unreasonable'),
        ('sensible', 'nonsensical'),
        ('logical', 'illogical'),
        ('rational', 'irrational'),
        ('sane', 'insane'),
        ('normal', 'abnormal'),
        ('typical', 'atypical'),
        ('usual', 'unusual'),
        ('common', 'rare'),
        ('ordinary', 'extraordinary'),
        ('mundane', 'exceptional'),
        ('average', 'extreme'),
        ('moderate', 'excessive'),
        ('balanced', 'unbalanced'),
        ('proportional', 'disproportional'),
        ('symmetrical', 'asymmetrical'),
        ('even', 'odd'),
        ('regular', 'irregular'),
        ('uniform', 'diverse'),
        ('homogeneous', 'heterogeneous'),
        ('consistent', 'inconsistent'),
        ('stable', 'unstable'),
        ('steady', 'unsteady'),
        ('constant', 'variable'),
        ('fixed', 'mobile'),
        ('stationary', 'moving'),
        ('static', 'dynamic'),
        ('inert', 'active'),
        ('passive', 'active'),
        ('idle', 'busy'),
        ('inactive', 'active'),
        ('dormant', 'active'),
        ('latent', 'manifest'),
        ('potential', 'actual'),
        ('theoretical', 'practical'),
        ('abstract', 'concrete'),
        ('conceptual', 'physical'),
        ('virtual', 'real'),
        ('digital', 'analog'),
        ('electronic', 'mechanical'),
        ('automated', 'manual'),
        ('automatic', 'manual'),
        ('programmed', 'spontaneous'),
        ('planned', 'improvised'),
        ('prepared', 'unprepared'),
        ('ready', 'unready'),
        ('equipped', 'unequipped'),
        ('armed', 'unarmed'),
        ('loaded', 'empty'),
        ('full', 'empty'),
        ('occupied', 'vacant'),
        ('inhabited', 'uninhabited'),
        ('populated', 'deserted'),
        ('crowded', 'empty'),
        ('dense', 'sparse'),
        ('thick', 'thin'),
        ('concentrated', 'diluted'),
        ('rich', 'poor'),
        ('wealthy', 'impoverished'),
        ('affluent', 'destitute'),
        ('prosperous', 'needy'),
        ('abundant', 'scarce'),
        ('plentiful', 'scarce'),
        ('ample', 'insufficient'),
        ('excess', 'shortage'),
        ('surplus', 'deficit'),
        ('profit', 'loss'),
        ('gain', 'loss'),
        ('increase', 'decrease'),
        ('growth', 'decline'),
        ('expansion', 'contraction'),
        ('inflation', 'deflation'),
        ('appreciation', 'depreciation'),
        ('rise', 'fall'),
        ('ascent', 'descent'),
        ('climb', 'descend'),
        ('up', 'down'),
        ('high', 'low'),
        ('tall', 'short'),
        ('elevated', 'depressed'),
        ('raised', 'lowered'),
        ('lifted', 'dropped'),
        ('floating', 'sinking'),
        ('flying', 'falling'),
        ('soaring', 'plummeting'),
        ('ascending', 'descending'),
        ('rising', 'setting'),
        ('waxing', 'waning'),
        ('growing', 'shrinking'),
        ('expanding', 'contracting'),
        ('swelling', 'shrinking'),
        ('inflating', 'deflating'),
        ('increasing', 'decreasing'),
        ('multiplying', 'dividing'),
        ('adding', 'subtracting'),
        ('positive', 'negative'),
        ('plus', 'minus'),
        ('credit', 'debit'),
        ('deposit', 'withdrawal'),
        ('income', 'expense'),
        ('revenue', 'cost'),
        ('earnings', 'losses'),
        ('profit', 'loss'),
        ('gain', 'loss'),
        ('benefit', 'harm'),
        ('advantage', 'disadvantage'),
        ('pro', 'con'),
        ('strength', 'weakness'),
        ('asset', 'liability'),
        ('virtue', 'vice'),
        ('merit', 'demerit'),
        ('quality', 'defect'),
        ('excellence', 'mediocrity'),
        ('perfection', 'imperfection'),
        ('flawless', 'flawed'),
        ('ideal', 'real'),
        ('utopian', 'dystopian'),
        ('heaven', 'hell'),
        ('paradise', 'inferno'),
        ('bliss', 'misery'),
        ('happiness', 'sadness'),
        ('joy', 'sorrow'),
        ('pleasure', 'pain'),
        ('comfort', 'discomfort'),
        ('relief', 'distress'),
        ('ease', 'difficulty'),
        ('simple', 'complex'),
        ('easy', 'hard'),
        ('effortless', 'laborious'),
        ('automatic', 'manual'),
        ('passive', 'active'),
        ('static', 'dynamic'),
        ('fixed', 'variable'),
        ('constant', 'changing'),
        ('stable', 'unstable'),
        ('steady', 'unsteady'),
        ('balanced', 'unbalanced'),
        ('equilibrium', 'disequilibrium'),
        ('harmony', 'discord'),
        ('peace', 'war'),
        ('calm', 'storm'),
        ('quiet', 'loud'),
        ('silent', 'noisy'),
        ('still', 'moving'),
        ('motionless', 'mobile'),
        ('stationary', 'moving'),
        ('inert', 'active'),
        ('passive', 'aggressive'),
        ('defensive', 'offensive'),
        ('protective', 'destructive'),
        ('constructive', 'destructive'),
        ('creative', 'destructive'),
        ('productive', 'counterproductive'),
        ('efficient', 'inefficient'),
        ('effective', 'ineffective'),
        ('successful', 'unsuccessful'),
        ('victorious', 'defeated'),
        ('winning', 'losing'),
        ('champion', 'loser'),
        ('leader', 'follower'),
        ('master', 'servant'),
        ('teacher', 'student'),
        ('expert', 'novice'),
        ('professional', 'amateur'),
        ('skilled', 'unskilled'),
        ('trained', 'untrained'),
        ('experienced', 'inexperienced'),
        ('veteran', 'rookie'),
        ('senior', 'junior'),
        ('elder', 'younger'),
        ('old', 'young'),
        ('ancient', 'modern'),
        ('antique', 'contemporary'),
        ('obsolete', 'current'),
        ('outdated', 'updated'),
        ('old-fashioned', 'fashionable'),
        ('traditional', 'innovative'),
        ('conservative', 'progressive'),
        ('conventional', 'unconventional'),
        ('orthodox', 'unorthodox'),
        ('mainstream', 'alternative'),
        ('popular', 'unpopular'),
        ('famous', 'obscure'),
        ('celebrated', 'unknown'),
        ('renowned', 'anonymous'),
        ('notable', 'insignificant'),
        ('significant', 'insignificant'),
        ('important', 'unimportant'),
        ('essential', 'nonessential'),
        ('critical', 'trivial'),
        ('vital', 'peripheral'),
        ('central', 'marginal'),
        ('primary', 'secondary'),
        ('major', 'minor'),
        ('dominant', 'submissive'),
        ('superior', 'inferior'),
        ('better', 'worse'),
        ('best', 'worst'),
        ('excellent', 'terrible'),
        ('outstanding', 'poor'),
        ('exceptional', 'mediocre'),
        ('extraordinary', 'ordinary'),
        ('remarkable', 'unremarkable'),
        ('special', 'common'),
        ('unique', 'typical'),
        ('rare', 'common'),
        ('scarce', 'abundant'),
        ('limited', 'unlimited'),
        ('finite', 'infinite'),
        ('bounded', 'unbounded'),
        ('restricted', 'unrestricted'),
        ('constrained', 'unconstrained'),
        ('confined', 'free'),
        ('imprisoned', 'liberated'),
        ('captive', 'free'),
        ('enslaved', 'emancipated'),
        ('oppressed', 'liberated'),
        ('subjugated', 'independent'),
        ('dependent', 'independent'),
        ('reliant', 'self-sufficient'),
        ('needy', 'self-reliant'),
        ('helpless', 'self-sufficient'),
        ('vulnerable', 'invulnerable'),
        ('exposed', 'protected'),
        ('defenseless', 'defended'),
        ('weak', 'strong'),
        ('fragile', 'robust'),
        ('delicate', 'sturdy'),
        ('sensitive', 'insensitive'),
        ('responsive', 'unresponsive'),
        ('reactive', 'unreactive'),
        ('volatile', 'stable'),
        ('unstable', 'stable'),
        ('erratic', 'consistent'),
        ('unpredictable', 'predictable'),
        ('random', 'deterministic'),
        ('chaotic', 'orderly'),
        ('disorganized', 'organized'),
        ('messy', 'neat'),
        ('cluttered', 'tidy'),
        ('dirty', 'clean'),
        ('soiled', 'pristine'),
        ('contaminated', 'pure'),
        ('polluted', 'clean'),
        ('toxic', 'nontoxic'),
        ('poisonous', 'harmless'),
        ('harmful', 'harmless'),
        ('dangerous', 'safe'),
        ('hazardous', 'secure'),
        ('risky', 'secure'),
        ('uncertain', 'certain'),
        ('doubtful', 'confident'),
        ('skeptical', 'believing'),
        ('questioning', 'accepting'),
        ('critical', 'approving'),
        ('negative', 'positive'),
        ('pessimistic', 'optimistic'),
        ('cynical', 'idealistic'),
        ('realistic', 'idealistic'),
        ('practical', 'theoretical'),
        ('pragmatic', 'idealistic'),
        ('materialistic', 'spiritual'),
        ('physical', 'mental'),
        ('tangible', 'intangible'),
        ('concrete', 'abstract'),
        ('specific', 'general'),
        ('particular', 'universal'),
        ('individual', 'collective'),
        ('personal', 'impersonal'),
        ('subjective', 'objective'),
        ('biased', 'unbiased'),
        ('prejudiced', 'impartial'),
        ('partial', 'impartial'),
        ('unfair', 'fair'),
        ('unjust', 'just'),
        ('inequitable', 'equitable'),
        ('unequal', 'equal'),
        ('different', 'same'),
        ('diverse', 'uniform'),
        ('varied', 'consistent'),
        ('heterogeneous', 'homogeneous'),
        ('mixed', 'pure'),
        ('composite', 'elemental'),
        ('complex', 'simple'),
        ('complicated', 'straightforward'),
        ('intricate', 'plain'),
        ('elaborate', 'basic'),
        ('fancy', 'plain'),
        ('ornate', 'simple'),
        ('decorated', 'unadorned'),
        ('embellished', 'plain'),
        ('detailed', 'vague'),
        ('specific', 'general'),
        ('explicit', 'implicit'),
        ('clear', 'unclear'),
        ('obvious', 'subtle'),
        ('apparent', 'hidden'),
        ('visible', 'invisible'),
        ('evident', 'obscure'),
        ('manifest', 'latent'),
        ('revealed', 'concealed'),
        ('disclosed', 'undisclosed'),
        ('exposed', 'hidden'),
        ('overt', 'covert'),
        ('public', 'private'),
        ('open', 'secret'),
        ('transparent', 'opaque'),
        ('honest', 'dishonest'),
        ('truthful', 'deceptive'),
        ('genuine', 'fake'),
        ('authentic', 'counterfeit'),
        ('real', 'artificial'),
        ('natural', 'synthetic'),
        ('organic', 'inorganic'),
        ('living', 'dead'),
        ('alive', 'dead'),
        ('animate', 'inanimate'),
        ('conscious', 'unconscious'),
        ('awake', 'asleep'),
        ('alert', 'drowsy'),
        ('attentive', 'distracted'),
        ('focused', 'unfocused'),
        ('concentrated', 'dispersed'),
        ('unified', 'divided'),
        ('integrated', 'segregated'),
        ('connected', 'disconnected'),
        ('linked', 'unlinked'),
        ('attached', 'detached'),
        ('joined', 'separated'),
        ('combined', 'isolated'),
        ('together', 'apart'),
        ('united', 'divided'),
        ('whole', 'partial'),
        ('complete', 'incomplete'),
        ('finished', 'unfinished'),
        ('done', 'undone'),
        ('accomplished', 'unaccomplished'),
        ('achieved', 'unachieved'),
        ('fulfilled', 'unfulfilled'),
        ('satisfied', 'unsatisfied'),
        ('content', 'discontent'),
        ('happy', 'unhappy'),
        ('pleased', 'displeased'),
        ('delighted', 'disappointed'),
        ('excited', 'bored'),
        ('enthusiastic', 'apathetic'),
        ('passionate', 'indifferent'),
        ('interested', 'disinterested'),
        ('engaged', 'disengaged'),
        ('involved', 'uninvolved'),
        ('committed', 'uncommitted'),
        ('dedicated', 'undedicated'),
        ('devoted', 'undevoted'),
        ('loyal', 'disloyal'),
        ('faithful', 'unfaithful'),
        ('trustworthy', 'untrustworthy'),
        ('reliable', 'unreliable'),
        ('dependable', 'undependable'),
        ('consistent', 'inconsistent'),
        ('stable', 'unstable'),
        ('steady', 'unsteady'),
        ('balanced', 'unbalanced'),
        ('even', 'uneven'),
        ('level', 'sloped'),
        ('flat', 'curved'),
        ('straight', 'crooked'),
        ('linear', 'nonlinear'),
        ('direct', 'indirect'),
        ('explicit', 'implicit'),
        ('express', 'implied'),
        ('stated', 'unstated'),
        ('spoken', 'unspoken'),
        ('verbal', 'nonverbal'),
        ('written', 'unwritten'),
        ('documented', 'undocumented'),
        ('recorded', 'unrecorded'),
        ('registered', 'unregistered'),
        ('official', 'unofficial'),
        ('formal', 'informal'),
        ('proper', 'improper'),
        ('correct', 'incorrect'),
        ('right', 'wrong'),
        ('true', 'false'),
        ('valid', 'invalid'),
        ('sound', 'unsound'),
        ('logical', 'illogical'),
        ('rational', 'irrational'),
        ('reasonable', 'unreasonable'),
        ('sensible', 'nonsensical'),
        ('wise', 'foolish'),
        ('intelligent', 'unintelligent'),
        ('smart', 'stupid'),
        ('clever', 'dull'),
        ('bright', 'dim'),
        ('brilliant', 'dull'),
        ('sharp', 'blunt'),
        ('acute', 'obtuse'),
        ('keen', 'dull'),
        ('perceptive', 'imperceptive'),
        ('insightful', 'superficial'),
        ('profound', 'shallow'),
        ('deep', 'shallow'),
        ('thorough', 'superficial'),
        ('comprehensive', 'limited'),
        ('complete', 'partial'),
        ('exhaustive', 'incomplete'),
        ('inclusive', 'exclusive'),
        ('universal', 'particular'),
        ('global', 'local'),
        ('international', 'national'),
        ('worldwide', 'regional'),
        ('cosmic', 'terrestrial'),
        ('celestial', 'terrestrial'),
        ('heavenly', 'earthly'),
        ('divine', 'human'),
        ('supernatural', 'natural'),
        ('magical', 'mundane'),
        ('mystical', 'practical'),
        ('spiritual', 'material'),
        ('sacred', 'profane'),
        ('holy', 'unholy'),
        ('blessed', 'cursed'),
        ('fortunate', 'unfortunate'),
        ('lucky', 'unlucky'),
        ('successful', 'unsuccessful'),
        ('victorious', 'defeated'),
        ('triumphant', 'vanquished'),
        ('winning', 'losing'),
        ('advancing', 'retreating'),
        ('progressing', 'regressing'),
        ('improving', 'deteriorating'),
        ('developing', 'declining'),
        ('growing', 'shrinking'),
        ('expanding', 'contracting'),
        ('increasing', 'decreasing'),
        ('rising', 'falling'),
        ('ascending', 'descending'),
        ('climbing', 'descending'),
        ('upward', 'downward'),
        ('forward', 'backward'),
        ('ahead', 'behind'),
        ('leading', 'following'),
        ('first', 'last'),
        ('primary', 'secondary'),
        ('principal', 'auxiliary'),
        ('main', 'subsidiary'),
        ('central', 'peripheral'),
        ('core', 'superficial'),
        ('essential', 'nonessential'),
        ('necessary', 'unnecessary'),
        ('required', 'optional'),
        ('mandatory', 'voluntary'),
        ('compulsory', 'elective'),
        ('forced', 'chosen'),
        ('imposed', 'selected'),
        ('dictated', 'elected'),
        ('commanded', 'requested'),
        ('ordered', 'suggested'),
        ('instructed', 'advised'),
        ('directed', 'guided'),
        ('controlled', 'autonomous'),
        ('regulated', 'unregulated'),
        ('restricted', 'unrestricted'),
        ('limited', 'unlimited'),
        ('finite', 'infinite'),
        ('bounded', 'unbounded'),
        ('definite', 'indefinite'),
        ('specific', 'general'),
        ('particular', 'universal'),
        ('concrete', 'abstract'),
        ('tangible', 'intangible'),
        ('physical', 'metaphysical'),
        ('material', 'immaterial'),
        ('substantial', 'insubstantial'),
        ('solid', 'fluid'),
        ('rigid', 'flexible'),
        ('stiff', 'pliable'),
        ('hard', 'soft'),
        ('firm', 'yielding'),
        ('tough', 'tender'),
        ('strong', 'weak'),
        ('powerful', 'powerless'),
        ('mighty', 'feeble'),
        ('forceful', 'gentle'),
        ('violent', 'peaceful'),
        ('aggressive', 'passive'),
        ('active', 'inactive'),
        ('energetic', 'lethargic'),
        ('vigorous', 'feeble'),
        ('dynamic', 'static'),
        ('lively', 'dull'),
        ('animated', 'lifeless'),
        ('vibrant', 'drab'),
        ('colorful', 'colorless'),
        ('bright', 'dim'),
        ('luminous', 'dark'),
        ('light', 'dark'),
        ('day', 'night'),
        ('dawn', 'dusk'),
        ('morning', 'evening'),
        ('sunrise', 'sunset'),
        ('beginning', 'end'),
        ('birth', 'death'),
        ('creation', 'destruction'),
        ('construction', 'demolition'),
        ('building', 'destroying'),
        ('making', 'breaking'),
        ('assembling', 'disassembling'),
        ('composing', 'decomposing'),
        ('synthesizing', 'analyzing'),
        ('combining', 'separating'),
        ('joining', 'splitting'),
        ('uniting', 'dividing'),
        ('connecting', 'disconnecting'),
        ('linking', 'unlinking'),
        ('attaching', 'detaching'),
        ('binding', 'unbinding'),
        ('tying', 'untying'),
        ('fastening', 'unfastening'),
        ('securing', 'releasing'),
        ('locking', 'unlocking'),
        ('closing', 'opening'),
        ('shutting', 'opening'),
        ('sealing', 'unsealing'),
        ('covering', 'uncovering'),
        ('hiding', 'revealing'),
        ('concealing', 'exposing'),
        ('masking', 'unmasking'),
        ('disguising', 'revealing'),
        ('camouflaging', 'highlighting'),
        ('obscuring', 'clarifying'),
        ('confusing', 'enlightening'),
        ('complicating', 'simplifying'),
        ('complex', 'simple')
    ]
    
    # Check for contradictions in the statement
    for term1, term2 in contradictions:
        if term1 in statement.lower() and term2 in statement.lower():
            # Check if terms are close to each other (within 5 words)
            words = statement.lower().split()
            term1_indices = [i for i, word in enumerate(words) if term1 in word]
            term2_indices = [i for i, word in enumerate(words) if term2 in word]
            
            for idx1 in term1_indices:
                for idx2 in term2_indices:
                    if abs(idx1 - idx2) <= 5:
                        return {
                            'is_valid': False,
                            'contradiction': f"'{term1}' and '{term2}'",
                            'reason': f"Statement contains contradictory terms '{term1}' and '{term2}' in close proximity"
                        }
    
    # Check for incomplete conditional statements
    if re.search(r'\b(if|when|while)\b', statement.lower()) and not re.search(r'\b(then|do|will|shall|should|must|can|could|would|might)\b', statement.lower()):
        return {
            'is_valid': False,
            'reason': "Statement contains a conditional clause without a consequent clause"
        }
    
    # Check for vague terms in short statements
    vague_terms = ['something', 'somehow', 'whatever', 'anything', 'stuff', 'things', 'it', 'them', 'those', 'these']
    if len(statement.split()) < 10 and any(term in statement.lower().split() for term in vague_terms):
        return {
            'is_valid': False,
            'reason': "Statement is too vague or ambiguous"
        }
    
    # If no issues found, statement is valid
    return {
        'is_valid': True
    }