name: Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Docker tools
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose-plugin

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install PyYAML>=6.0
          pip install docker-compose
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build and deploy
        run: |
          docker compose build
          docker compose up -d

      - name: Rollback on failure
        if: failure()
        run: |
          echo "❌ Deployment failed, initiating rollback..."
          docker compose down || echo "Rollback completed with warnings"
          exit 1  # Ensure the step fails to mark job as failed
